import 'package:alarmi/features/my/models/noti.dart';
import 'package:alarmi/features/my/models/noti_type.dart';

List<Noti> notifications = [
  Noti(
    notiId: 'noti6',
    sender: 'admin',
    receiver: '스카이',
    notiDate: '2025-05-03 00:00:00',
    notiType: NotiType.ReceiverWakeUp,
    teamName: null,
    senderThumb: null,
    hasRead: false,
  ),
  Noti(
    notiId: 'noti5',
    sender: 'admin',
    receiver: '나',
    notiDate: '2025-05-03 00:00:00',
    notiType: NotiType.WeekAccomplished,
    teamName: null,
    senderThumb: null,
    hasRead: false,
  ),
  Noti(
    notiId: 'noti4',
    sender: '쳡쳡',
    receiver: '죨',
    notiDate: '2025-05-03 00:00:00',
    notiType: NotiType.MemberInviteSomeoneToTeam,
    teamName: '새벽',
    senderThumb: null,
    hasRead: false,
  ),
  Noti(
    notiId: 'noti3',
    sender: '쳡쳡',
    receiver: '나',
    notiDate: '2025-05-02 00:00:00',
    notiType: NotiType.BeInvitedToTeam,
    teamName: '새벽',
    senderThumb: null,
    hasRead: false,
  ),
  Noti(
    notiId: 'noti2',
    sender: 'admin',
    receiver: '쥴',
    notiDate: '2025-05-02 00:00:00',
    notiType: NotiType.AcceptFriendship,
    teamName: null,
    senderThumb: null,
    hasRead: false,
  ),
  Noti(
    notiId: 'noti1',
    sender: 'admin',
    receiver: '쥴',
    notiDate: '2025-05-02 00:00:00',
    notiType: NotiType.FriendRequest,
    teamName: null,
    senderThumb: null,
    hasRead: false,
  ),
  Noti(
    notiId: 'noti0',
    sender: '쳡쳡',
    receiver: '나',
    notiDate: '2025-05-01 00:00:00',
    notiType: NotiType.ReceiveFriendRequest,
    teamName: null,
    senderThumb: null,
    hasRead: false,
  ),
];
